spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  messages:
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://129.211.189.152:3306/ayqcby
    username: root
    password: wn123456
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

  servlet:
    multipart:
      max-file-size:  100MB
      max-request-size:  200MB

file:
  uploadFolder: D://upfile/
  staticAccessPath: /upfile/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.ayqcby.domain
  configLocation: classpath:mybatis-config.xml

logging:
  level:
    com.project: debug
    org.springframework: warn

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
